// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// logl_cxx
List logl_cxx(NumericVector ThetaI, NumericVector YY, NumericMatrix XX);
RcppExport SEXP sdsBAT_logl_cxx(SEXP ThetaISEXP, SEXP YYSEXP, SEXP XXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type ThetaI(ThetaISEXP);
    Rcpp::traits::input_parameter< NumericVector >::type YY(YYSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type XX(XXSEXP);
    rcpp_result_gen = Rcpp::wrap(logl_cxx(ThetaI, YY, XX));
    return rcpp_result_gen;
END_RCPP
}
