# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Ornstein Uhelenbeck Likelihood calculation
#'
#' @export
logl_cxx <- function(ThetaI, YY, XX) {
    .Call('sdsBAT_logl_cxx', PACKAGE = 'sdsBAT', ThetaI, YY, XX)
}

